version: '3'

services:

  pizzabot-node:
    volumes:
      - frontend:/frontend
    build:
      context: ..
      dockerfile: ./backend/node/Dockerfile

  pizzabot-flask:
    volumes:
      - ./app:/app
      - frontend:/frontend
    environment:
      - FLASK_APP=app/server.py
      - FLASK_DEBUG=${FLASK_DEBUG}
      - PYTHONUNBUFFERED=1
      - 'RUN=gunicorn -c /app/gunicorn_conf.py app.__main__:app'
    command: gunicorn -c /app/gunicorn_conf.py app.__main__:app
    build:
      context: ..
      dockerfile: ./backend/flask/Dockerfile

  pizzabot-nginx:
    image: nginx:1.21.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
    ports:
      - "127.0.0.1:${PORT}:80"


volumes:
  frontend: